minApprovals:
  COLLABORATOR: 0
  OWNER: 0

requiredLabels:
  - dependencies

deleteBranchAfterMerge: true
mergeMethod: squash
updateBranch: true

mergeCommitMessage: |
  {title} (#{number})

  {body}
