name: Auto Merge Dependabot Pull Request

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write

jobs:
  auto-merge-dependabot-pull-request:
    name: Auto Merge Dependabot Pull Request

    if: ${{ github.actor == 'dependabot[bot]' }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_URL: ${{ github.event.pull_request.html_url }}

    steps:
      - name: Approve
        run: gh pr review --approve $PR_URL

      - name: Merge
        run: gh pr merge $PR_URL
