name: Auto Approval Dependabot's Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - edited
  pull_request_review:
    types:
      - dismissed

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approval-depenabots-pull-request:
    name: Approve

    runs-on: ubuntu-latest
    timeout-minutes: 10

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Approve
        uses: dkhmelenko/autoapproval@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
