name: Commit Lint Messages

on:
  pull_request:
  push:

jobs:
  commit-lint-messages:
    if: github.actor != 'dependabot[bot]'

    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Commit
        uses: wagoid/commitlint-github-action@v5
