name: Commit Lint

on:
  pull_request:
    branches-ignore:
      - dependabot/*
  push:
    branches-ignore:
      - dependabot/*

jobs:
  commit-lint:
    name: Commit Lint

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Lint
        uses: ahmadnassri/action-commit-lint@v2
