name: Lint Commit Messages

on:
  pull_request:
  push:

jobs:
  lint-commit-messages:
    if: ${{ github.actor != 'dependabot[bot]' }}

    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint
        uses: wagoid/commitlint-github-action@v5
