name: Commit Lint Messages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  commit-lint-messages:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Commit Lint
        uses: wagoid/commitlint-github-action@v5
