name: Coverage

on:
  pull_request:
    branches:
      - main
      - feature/coverage
  push:
    branches:
      - main
      - feature/coverage

jobs:
  coverage:
    name: Coverage

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up BunJS
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Coverage
        run: bun spec:coverage

      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
