name: Create Pull Request

on:
  push:

jobs:
  create-pull-request:
    name: Create Pull Request

    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.merged == false }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: main
          PULL_REQUEST_TITLE: ${{ github.event.head_commit.message }}
        uses: vsoch/pull-request-action@master
