name: Dependabot auto merge

on: pull_request

env:
  PR_URL: ${{ github.event.pull_request.html_url }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    name: Merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ env.GITHUB_TOKEN }}

      - name: Approve a Pull Request
        run: gh pr review --approve '$PR_URL'

      - name: Enable Auto-merge For Dependabot Pull Requests
        run: gh pr merge --auto --merge --squash '$PR_URL'
