name: EditorConfig

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  editor-config:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: EditorConfig Lint
        run: npm run editorconfig:lint
