name: Markdown

on:
  workflow_run:
    workflows:
      - CodeQL
    types:
      - completed
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  markdown:
    name: Markdown

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up BunJS
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Lint
        run: bun lint:md
