name: Markdown

on:
  workflow_run:
    workflows:
      - EditorConfig
    types:
      - completed
  pull_request:
  push:
    branches:
      - main
    # paths:
    #   - '**/*.md'

jobs:
  markdown:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Paths filter
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            - markdown:
              - added|modified: '**/*.md'

      - name: Setup Node
        if: ${{ steps.filter.outputs.markdown == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Markdown
        run: npm run markdown:lint
