name: Mocha

on:
  workflow_run:
    workflows:
      - EditorConfig
      - ESLint
      - Markdown
      - Prettier
    types:
      - completed
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*.ts'
  push:
    branches:
      - main
    paths:
      - 'src/**/*.ts'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Tests
        run: npm run test
