name: Pre commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install pip
        run: pip install pre-commit

      - name: Pre Commit Version
        run: pre-commit --version

      - name: Pre Commit Install
        run: pre-commit install

      - name: Pre commit run all file
        run: pre-commit run --all-files
