name: Pre commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip

      - name: Pre-commit Action
        uses: pre-commit/action@v3.0.0
