name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
            conventional-changelog-conventionalcommits@4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
