name: Semantic pull request
# 1 approve
# commit lint
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pull-request:
    name: Validate Pull Request Title
    runs-on: ubuntu-latest

    steps:
      - name: Validate
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
