name: Semantic pull request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  validate-pull-request-title:
    if: ${{ github.actor != 'dependabot[bot]' }}

    name: Validate Pull Request title
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Validate
        uses: amannn/action-semantic-pull-request@v5
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
