name: Semantic pull request title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pull-request-title:
    runs-on: ubuntu-latest
    steps:
      - name: Semantic pull request title
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types:
            - breaking
            - chore
            - ci
            - docs
            - feat
            - fix
            - refactor
            - security
            - style
            - test
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject '{subject}' found in the pull request title '{title}'
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          wip: true
          validateSingleCommit: false
